# Generated by Django 4.0 on 2022-01-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedlink',
            name='short_url',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
